DROP TABLE IF EXISTS admin_accounts;
CREATE TABLE admin_accounts (
  USER_ID INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  USERNAME varchar(20) UNIQUE NOT NULL,
  PASSWORD_HASH varchar(32) NOT NULL,
  SETTINGS INTEGER
);
DROP TABLE IF EXISTS article;
CREATE TABLE article (
  ID INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  TITLE varchar(70) UNIQUE NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  CONTENT BLOB NOT NULL,
  AUTHOR varchar(30) NOT NULL,
  CREATION_DATE real NOT NULL,
  SETTINGS integer
);
DROP TABLE IF EXISTS article_comments;
CREATE TABLE article_comments (
  ID INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  TITLE varchar(70) UNIQUE NOT NULL,
  CONTENT TEXT NOT NULL,
  AUTHOR varchar(30) NOT NULL,
  CREATION_DATE real NOT NULL,
  SETTINGS integer
);
